---
- name: Preparar el servidor para despliegue
  hosts: webservers
  become: true # Esto hace que use sudo para todo xd
  vars:
    docker_users:
      - ubuntu
  tasks:
    - name: Actualizar cache de apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar paquetes necesarios para HTTPS
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
        state: present

    - name: Crear directorio para llave GPG de Docker
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Eliminar llave GPG corrupta si existe
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Eliminar repositorio Docker anterior
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Descargar y configurar llave GPG oficial de Docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

    - name: Configurar repositorio estable de Docker
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Actualizar cache de apt de nuevo (tras agregar repo de Docker)
      apt:
        update_cache: yes

    - name: Instalar docker Engine y Docker Compose Plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Agregar usuario ubuntu al grupo docker
      user:
        name: "ubuntu"
        groups: docker
        append: yes
        # Esto permite ejecutar comandos con Docker sin usar SUDO

    - name: Iniciar y habilitar servicio Docker
      systemd:
        name: docker
        state: started
        enabled: yes
